### ISSUE TITLE
不小心选择内部版本

### ISSUE THREAD

**Issue by takaximina** [arco-design/arco-cli#10]
不小心选择的内部版本，怎么切回git版本的
![image](https://user-images.githubusercontent.com/17963179/143767283-dd537c65-9b04-4cb1-b4a5-c1b7918adb5c.png)

**Comment by MisterLuffy** [comment]
`arco env -s` 即可切换环境。
![image](https://user-images.githubusercontent.com/29861850/143980661-94bd1350-32da-4208-b4e9-1728ba6508f8.png)
