### ISSUE TITLE
build:component:es ts 编译可以复制一下资源文件吗？

### ISSUE THREAD

**Issue by huangyingwen** [arco-design/arco-cli#13]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-cli/issues)

## 现有案例
选择 babel 编译时，gulpTS(tsconfig.compilerOptions) 不复制资源文件，但是 js 文件目录都变了，之后 babel 编译会报找不到文件，例如 svg 文件

## 预期解决问题
TS_COMPILER='babel' arco-scripts build:component:es

选择 babel 编译时，gulpTS(tsconfig.compilerOptions) 之后先把资源文件复制一下，例如 img 文件等，为接下来 babel 处理提供对应的资源文件

**Comment by MisterLuffy** [comment]
@arco-design/arco-scripts@1.25.12
