### ISSUE TITLE
文档站点支持添加一级菜单

### ISSUE THREAD

**Issue by hehuangz** [arco-design/arco-cli#14]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-cli/issues)

## What are the similar cases of this feature
arco文档官网的左侧导航

## What problem does this feature solve?
不同类型的文档太多，希望通过一级菜单划分更加清晰

**Comment by MisterLuffy** [comment]
升级 `@arco-design/arco-doc-site > 1.7.0`，团队站点的左侧菜单将保持与本地目录层级一致。
修改站点项目的 `.config/main.js` 中的字段可以自定义菜单配置，包括最大允许的子菜单层级，菜单排序规则：
```
module.exports = {
  site: {
    menu: {
      maxSubMenuLevel: 2,
      sortRule: { 'submenu1': [ 'item2', 'item1'] }
    }
  }
};
```
