### ISSUE TITLE
vite react 模版 .gitignore 中缺失dist，package.json缺失build脚本

### ISSUE THREAD

**Issue by zsytssk** [arco-design/arco-cli#21]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-cli/issues)

## Basic Info 
- **Package Name And Version:** acro-cli@1.26.0
- **Browser:** chrome98.0.4758.109
- **Reproduction Link:** https://codesandbox.io/s/fervent-bush-i68nts

## Extra info
这个不需要提供 ` Reproduction Link` 我就瞎写了一个。

## What is expected?
.gitignore 中有dist，package.json中有build脚本

## Steps to reproduce
1. 安装acro-cli最新版
2. acro init test
选择 react -> vite -> acroDesignPro -> 简单模版 生成项目文件

**Comment by MisterLuffy** [comment]
@yuhan0709 关于 React Pro 的优化问题。

**Comment by yuhan0709** [comment]
收到哈～
