### ISSUE TITLE
在Arco Pro 最佳实践文档指引下安装运行之后报错

### ISSUE THREAD

**Issue by Jazei** [arco-design/arco-cli#23]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-cli/issues)

## Basic Info 
- **Package Name And Version:** arco-cli@1.26.0
- **System:** win10
- **Browser:** chrome99.0.4844.51
- **Reproduction Link:** https://arco.design/vue/docs/pro/start

## What is expected?
如何导致的，如何解决

## Steps to reproduce
按照最佳实践文档指引下安装运行之后报错Uncaught SyntaxError: Not available in legacy mode

**Comment by MisterLuffy** [comment]
关于 VuePro 的相关的问题请移步至 [此仓库](https://github.com/arco-design/arco-design-pro-vue) 创建 issue。
我找到了这个 [回答](https://githubhot.com/repo/intlify/vite-plugin-vue-i18n/issues/102)，可以尝试一下是否有帮助
