### ISSUE TITLE
ssh 无法正常创建项目

### ISSUE THREAD

**Issue by mdddj** [arco-design/arco-cli#24]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-cli/issues)

## 基本信息 
- **依赖包名 及 版本:** new
- **浏览器版本:** chrome99.0.4844.74
- **复现地址:** http://baidu.com

## 预期结果
正常创建

看图
<img width="552" alt="image" src="https://user-images.githubusercontent.com/29020213/158532328-460d76f4-345b-4beb-8fb3-a8f9c4ad5c2b.png">

**Comment by MisterLuffy** [comment]
可以正常访问这个接口吗 https://arco.design/material/api/getHostInfo

**Comment by mdddj** [comment]
> 可以正常访问这个接口吗 https://arco.design/material/api/getHostInfo

可以的 
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/29020213/159243463-78e0025c-9954-4fd2-9259-db24dde9b7dd.png">

**Comment by MisterLuffy** [comment]
> > 可以正常访问这个接口吗 https://arco.design/material/api/getHostInfo
> 
> 可以的 <img alt="image" width="1158" src="https://user-images.githubusercontent.com/29020213/159243463-78e0025c-9954-4fd2-9259-db24dde9b7dd.png">

看报错应该是[这行代码](https://github.com/arco-design/arco-cli/blob/main/packages/arco-cli/src/env.ts#L38)的报错，但接口数据又是正常的，方便的话可以帮忙本地调试一下🙏
