### ISSUE TITLE
yarn add:package -- foo命令报错

### ISSUE THREAD

**Issue by guccihuiyuan** [arco-design/arco-cli#26]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-cli/issues)

## Basic Info 
- **Reproduction Link:** https://www.baidu.com
- **Browser:** firefox99.0
- **Package Name And Version:** foo

## What is expected?
能正常创建项目

## Extra info
Command Error: npm install @arco-materials/template-core

**Comment by MisterLuffy** [comment]
麻烦手动运行一下 `npm install @arco-materials/template-core` ，贴下详细的报错信息。
