### ISSUE TITLE
arco init project ---> select "组件" ---> npm run dev ---> ERROR in ./generated-stories-entry.js Module not found: Error: Can't resolve './stories'

### ISSUE THREAD

**Issue by githubhwen** [arco-design/arco-cli#29]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-cli/issues)

## Basic Info 
- **Package Name And Version:** 1.27.0
- **System:** mac os m1
- **Browser:** chrome100.0.4896.127
- **Reproduction Link:** https://codesandbox.io/s/gallant-cherry-d5jsjl

## Extra info
node v16.14.2
arco-cli 1.27.0

## What is expected?
Program runs without error

## Steps to reproduce
arco init project ---> react ---> select "组件" ---> npm run dev ---> ERROR in ./generated-stories-entry.js Module not found: Error: Can't resolve './stories'
ERROR in ./generated-stories-entry.js
Module not found: Error: Can't resolve './stories' in '/Desktop/project/doc'
 @ ./generated-stories-entry.js 7:37-123
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js

**Comment by MisterLuffy** [comment]
Is there a directory named `stories` in your project？It's the entry of storybook.
