### ISSUE TITLE
Is there any possibility for `arco-material-doc-site` to support a storybook site conversion?

### ISSUE THREAD

**Issue by zhoujinfu** [arco-design/arco-cli#37]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
To support an existed storybook site quick convert to  standard `arco-material-doc-site` as a team site. 

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by MisterLuffy** [comment]
Sry, it's too hard to achieve. All you need to do is to adapt the demo of storybook to fit Arco's team-site.

**Comment by zhoujinfu** [comment]
Got it, thx all the same.
