### ISSUE TITLE
arco init yourProjectName 无法成功建立项目

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-cli#38]
**Describe the bug**
如标题

**To Reproduce**
安装`npm i arco-cli -g`
初始化`arco init yourProjectName`

**Expected behavior**
能成功执行

**Screenshots**
![image](https://user-images.githubusercontent.com/93666053/174331729-ae9ab26a-77fe-4174-9c0e-7795508ba208.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - node version v16.13.1

**Other Content**
虽然提示初始化完成，可以启动，但是执行`npm run dev`也是报错
![image](https://user-images.githubusercontent.com/93666053/174332264-d8d87338-4246-4307-8cda-fe9bd6382e04.png)

**Comment by ZhongMingKun** [comment]
+1

**Comment by ZhongMingKun** [comment]
> https://github.com/ZhongMingKun/-arco-design-vue-pro-components 改用了@storybook/builder-vite，运行是没报错了，不知道还缺什么配置，页面加载失败

需要升级@storybook全家桶到v6.4.0以上，还不知道部署有没有坑

**Comment by ZhongMingKun** [comment]
### 暂时测试是 builder改为webpack5后可用

1. 安装依赖
```bash
$ yarn add -D @storybook/builder-webpack5 @storybook/manager-webpack5
```

2. 运行

```bash
$ yarn dev
```

**Comment by ZhongMingKun** [comment]
> 你arco init 是vue、组件库类型吗

回看下我的回复，添加了一下webpack5的使用

**Comment by MisterLuffy** [comment]
> ![image](https://user-images.githubusercontent.com/93666053/176469864-6f804af4-ca3b-493d-b44f-ea571d53e3f4.png) ![image](https://user-images.githubusercontent.com/93666053/176470311-6ec3402a-5205-4b60-bb03-4770742e82c8.png)
> 
> 建了空stories目录，yarn dev没报错了，控制台报错`Uncaught ReferenceError: exports is not defined`，界面转圈圈

因为新建的项目是没有组件的，所以需要 `yarn add:component Button` 添加一个组件即可。

**Comment by MisterLuffy** [comment]
> ### 暂时测试是 builder改为webpack5后可用
> 1. 安装依赖
> 
> ```shell
> $ yarn add -D @storybook/builder-webpack5 @storybook/manager-webpack5
> ```
> 
> 2. `.storybook/main.js`里面加上 `core: { builder: 'webpack5' }`;
> 
> 具体代码：
> 
> ```diff
> const path = require('path');
> const glob = require('glob');
> const fs = require('fs-extra');
> 
> const packagePaths = glob.sync('packages/*');
> 
> const lessRegex = /\.less$/;
> const lessModuleRegex = /\.module\.less$/;
> 
> function getLoaderForStyle(cssOptions) {
>   return [
>     {
>       loader: 'style-loader',
>     },
>     {
>       loader: 'css-loader',
>       options: cssOptions,
>     },
>     {
>       loader: 'less-loader',
>       options: {
>         lessOptions: {
>           javascriptEnabled: true,
>         },
>       },
>     },
>   ];
> }
> 
> module.exports = {
> +  core: { builder: 'webpack5' },
>   stories: ['../packages/**/stories/*.@(js|jsx|ts|tsx)'],
>   addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
>   webpackFinal: (config) => {
>     // 为 storybook 添加 packages 中项目的 alias
>     packagePaths.forEach((_path) => {
>       const packageJson = fs.readJsonSync(path.resolve(_path, 'package.json'));
>       const dirSourceFile =
>         packageJson.arcoMeta && packageJson.arcoMeta.type === 'vue-library'
>           ? 'components'
>           : 'src';
>       config.resolve.alias[`${packageJson.name}$`] = path.resolve(
>         _path,
>         dirSourceFile
>       );
>     });
> 
>     // less
>     config.module.rules.push({
>       test: lessRegex,
>       exclude: lessModuleRegex,
>       use: getLoaderForStyle(),
>     });
> 
>     // less css modules
>     config.module.rules.push({
>       test: lessModuleRegex,
>       use: getLoaderForStyle({ modules: true }),
>     });
> 
>     // svg modules
>     config.module.rules.push({
>       test: /\.svg$/,
>       use: ['vue-loader', 'vue-svg-loader'],
>     });
> 
>     return config;
>   },
> };
> ```
> 
> 3. 运行
> 
> ```shell
> $ yarn dev
> ```

试了一下确实可行，我们更新一下项目模板的配置到 Webpack 5。

**Comment by azhengyongqin** [comment]
https://github.com/arco-design/arco-cli/issues/38#issuecomment-1170710705

Windows环境下依然报错，麻烦解决windows下的环境
![image](https://user-images.githubusercontent.com/18138282/213135125-8a4205b1-2ca8-4f4d-817b-1833f343e079.png)
