### ISSUE TITLE
arco-cli 无法初始化项目报错Error: Failed to copy project content

### ISSUE THREAD

**Issue by AdvanceOrange** [arco-design/arco-cli#39]
**Describe the bug**
PS C:\Users\***\Desktop\study_vue\hello-arco-pro> arco init hello-arco-pro

        ___                    ____            _
       /   |  ______________  / __ \___  _____(_)___ _____
      / /| | / ___/ ___/ __ \/ / / / _ \/ ___/ / __ `/ __ \
     / ___ |/ /  / /__/ /_/ / /_/ /  __(__  ) / /_/ / / / /
    /_/  |_/_/   \___/\____/_____/\___/____/_/\__, /_/ /_/
                                             /____/

                                                v1.26.1

? 请选择你希望使用的技术栈 Vue
? 请选择所要创建项目的类型 Arco Pro 项目
? 请选择 Arco Pro 模板 完整版（包含所有页面）

正在初始化项目于 C:\Users\***\Desktop\study_vue\hello-arco-pro\hello-arco-pro
√ 获取项目模板成功
× 模板内容拷贝失败
Error: Failed to copy project content.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

    at module.exports (C:\Users\***\.arco_template_cache\1655866434222\node_modules\arco-design-pro-vue\.arco-cli\init.js:25:13)
    at C:\Program Files\node-v16.15.1-win-x64\node_modules\node_global\node_modules\arco-cli\node_modules\arco-cli-create-project\lib\index.js:129:23
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\node-v16.15.1-win-x64\node_modules\node_global\node_modules\arco-cli\node_modules\arco-cli-create-project\lib\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: EBUSY: resource busy or locked, rmdir 'C:\Users\***\.arco_template_cache\1655866434222\node_modules\arco-design-pro-vue'
node:fs:1180
  return handleErrorFromBinding(ctx);
         ^

Error: EBUSY: resource busy or locked, rmdir 'C:\Users\***\.arco_template_cache\1655866434222\node_modules\arco-design-pro-vue'
    at Object.rmdirSync (node:fs:1180:10)
    at rmdirSync (C:\Program Files\node-v16.15.1-win-x64\node_modules\node_global\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:264:13)
    at rimrafSync (C:\Program Files\node-v16.15.1-win-x64\node_modules\node_global\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:243:7)
    at C:\Program Files\node-v16.15.1-win-x64\node_modules\node_global\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:279:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Program Files\node-v16.15.1-win-x64\node_modules\node_global\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:279:26)
    at rmdirSync (C:\Program Files\node-v16.15.1-win-x64\node_modules\node_global\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:269:7)
    at rimrafSync (C:\Program Files\node-v16.15.1-win-x64\node_modules\node_global\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:243:7)
    at C:\Program Files\node-v16.15.1-win-x64\node_modules\node_global\node_modules\arco-cli\node_modules\fs-extra\lib\remove\rimraf.js:279:39
    at Array.forEach (<anonymous>) {
  errno: -4082,
  syscall: 'rmdir',
  code: 'EBUSY',
  path: 'C:\\Users\\***\\.arco_template_cache\\1655866434222\\node_modules\\arco-design-pro-vue'
}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10
 - node version v16.15.1

**Additional context**

**Comment by YangYouYong** [comment]
mac 端同样报错, 使用VUE-> Arco Pro 项目模版

✔ 获取项目模板成功
✖ 模板内容拷贝失败
Error: Failed to copy project content.
npm WARN config production Use --omit=dev instead.

at module.exports (/Users/xxx/.arco_template_cache/1655866634338/node_modules/arco-design-pro-vue/.arco-cli/init.js:25:13)
at /usr/local/lib/node_modules/arco-cli/node_modules/arco-cli-create-project/lib/index.js:129:23
at Generator.next (<anonymous>)
at fulfilled (/usr/local/lib/node_modules/arco-cli/node_modules/arco-cli-create-project/lib/index.js:5:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by MisterLuffy** [comment]
![image](https://user-images.githubusercontent.com/29861850/174958437-4e138279-2cf9-4749-ba86-b8e4f300eaf9.png)
我在本地没有复现，还有更多信息吗

**Comment by MisterLuffy** [comment]
方便的话可以试下直接克隆这个[仓库](https://github.com/arco-design/arco-design-pro-vue/blob/main/package.json#L11)初始化项目，`arco-cli` 也是调用的这个命令实现模板内容拷贝。

**Comment by AdvanceOrange** [comment]
我的npm版本是：8.1.2 ，执行 npm install 时需要携带这个参数 --legacy-peer-deps，目前项目成功运行

**Comment by YangYouYong** [comment]
降级node 到16.13.2 正常跑通不报错. @AdvanceOrange

**Comment by fangmuke** [comment]
> 降级node 到16.13.2 正常跑通不报错. @AdvanceOrange

docker环境下依旧报错
```
✖ Project dependency installation failed, you can try to manually install them later
Error: Command 「npm install」 executed failed:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: arco-design-pro-vue@1.0.0
npm ERR! Found: eslint@8.7.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.7.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb-base@14.2.1
npm ERR! node_modules/eslint-config-airbnb-base
npm ERR!   dev eslint-config-airbnb-base@"^14.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-01T03_39_51_700Z-debug.log

 arco-init  Project init failed!
Error: spawnSync yarn ENOENT
```

**Comment by AdvanceOrange** [comment]
@fangmuke npm install 时需要携带这个参数 --legacy-peer-deps

**Comment by wenner** [comment]
我也遇到了同样的问题

**Comment by Wngzh** [comment]
```Java
npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.       
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'F:\\arco\\node_modules\\optipng-bin',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'F:\arco\node_modules\optipng-bin'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'F:\\arco\\node_modules\\optipng-bin'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'F:\\arco\\node_modules\\mozjpeg',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'F:\arco\node_modules\mozjpeg'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'F:\\arco\\node_modules\\mozjpeg'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'F:\\arco\\node_modules\\optipng-bin',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'F:\arco\node_modules\optipng-bin'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'F:\\arco\\node_modules\\optipng-bin'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'F:\\arco\\node_modules\\mozjpeg',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'F:\arco\node_modules\mozjpeg'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'F:\\arco\\node_modules\\mozjpeg'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path F:\arco\node_modules\jpegtran-bin
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node lib/install.js
npm ERR! compiling from source
npm ERR! unable to verify the first certificate
npm ERR! jpegtran pre-build test failed
npm ERR! Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "touch configure.ac aclocal.m4 configure Makefile.am Makefile.in"
npm ERR! 'touch' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
npm ERR! ���������ļ���
npm ERR!
npm ERR!
npm ERR!     at F:\arco\node_modules\bin-build\node_modules\execa\index.js:231:11
npm ERR!     at runMicrotasks (<anonymous>)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async Promise.all (index 0)
```
有什么解决方法吗？
