### ISSUE TITLE
arco init hello-arco-pro 选GitHub授权登录后出现“请提交你的 Git 修改后继续操作”

### ISSUE THREAD

**Issue by swurtheone** [arco-design/arco-cli#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - node version [e.g. v16.13.1]

**Additional context**

**Comment by swurtheone** [comment]
![image](https://user-images.githubusercontent.com/31538827/174956029-deda72d2-313f-47f5-bc6a-ec459a4f2a66.png)

**Comment by MisterLuffy** [comment]
`arco init` 之前需要保证 Git 暂存区是干净的，把已有的修改提交一下即可。
