### ISSUE TITLE
创建vue 组件库物料项目安装依赖后运行报错

### ISSUE THREAD

**Issue by yanbowe** [arco-design/arco-cli#41]
**Describe the bug**
新建vue 组件库物料项目安装后报如下错误
 DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
0% compilingERR! TypeError: Cannot read properties of undefined (reading 'get')

**To Reproduce**
1. arco init demo
2. 选择vue
3. 选择组件库, 输入npm包名，输入物料标题，输入描述，输入npm版本号0.1.0，选择关键词
4. 等待下载依赖
5. yarn install 后yarn dev报错

**Expected behavior**
![image](https://user-images.githubusercontent.com/43030980/175478236-e4ed990c-da78-419e-ba54-164546030095.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS10.15.7
 - node version [e.g. v16.15.0]
- arco-cli [v1.27.1]
**Additional context**

**Comment by MisterLuffy** [comment]
可参考 [此方案](https://github.com/arco-design/arco-cli/issues/38#issuecomment-1162911167) 解决，或重新创建物料项目（项目模板）已更新。
