### ISSUE TITLE
初始化项目报错：AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by wuyansongs** [arco-design/arco-cli#42]
<img width="865" alt="屏幕截图 2022-06-29 153249" src="https://user-images.githubusercontent.com/19507788/176379294-95724ab7-ccd6-4a24-aa3c-e24975fb027a.png">

运行在 WSL2 ubuntu

**Comment by MisterLuffy** [comment]
可以参考这个 [解决方案](https://github.com/arco-design/arco-cli/issues/38#issuecomment-1162911167)，或者重新创建一个项目（项目模板已更新）。

**Comment by MisterLuffy** [comment]
你的环境可以访问这个接口不 https://arco.design/material/api/getHostInfo

**Comment by wuyansongs** [comment]
<img width="911" alt="屏幕截图" src="https://user-images.githubusercontent.com/19507788/176698077-42763709-8933-44ee-8fb7-a5f8f77aac22.png">

用curl可以 有工具要求吗

**Comment by MisterLuffy** [comment]
我这边没有什么思路，可能需要你克隆一下仓库帮忙排查一下

**Comment by WangShayne** [comment]
same issue

**Comment by WangShayne** [comment]
```
data: '<html>\r\n' +
      '<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n' +
      '<body bgcolor="white">\r\n' +
      '<center><h1>400 Bad Request</h1></center>\r\n' +
      '<center>The plain HTTP request was sent to HTTPS port</center>\r\n' +
      '<hr><center>nginx</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n'
```

@MisterLuffy nginx相关配置的问题

**Comment by WangShayne** [comment]
我本机流量通过http代理转发 http://127.0.0.1:1080  
暂时通过添加NO_PROXY arco.design解决
