### ISSUE TITLE
yarn add:component button 生成的模板没有替换组件名

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-cli#43]
1. 刚刚重新`arco-cli init`的项目
2. 运行`yarn add:component button`，生成的文件没有替换成输入的button
3. 手动替换后运行，控制台报错`Uncaught ReferenceError: exports is not defined`

![image](https://user-images.githubusercontent.com/93666053/176717076-6bf382d4-2e6c-4ca4-9159-caac27510e06.png)
![image](https://user-images.githubusercontent.com/93666053/176716756-8f24153a-7e73-42da-8f6a-53319c574aca.png)

**Comment by MisterLuffy** [comment]
我这边没有 windows 环境，方便的话可以排查一下可以给这个[仓库](https://github.com/arco-design/arco-material-template/blob/main/packages/template-core/vue/scripts(%24-l)/add-component.js)提个 PR。添加组件的脚本位于项目的 `scripts/add-component.js`。

**Comment by yanbowe** [comment]
> 我这边没有 windows 环境，方便的话可以排查一下可以给这个[仓库](https://github.com/arco-design/arco-material-template/blob/main/packages/template-core/vue/scripts(%24-l)/add-component.js)提个 PR。添加组件的脚本位于项目的 `scripts/add-component.js`。

macos也不行

**Comment by bqzhaoyan** [comment]
> > 我这边没有 windows 环境，方便的话可以排查一下可以给这个[仓库](https://github.com/arco-design/arco-material-template/blob/main/packages/template-core/vue/scripts(%24-l)/add-component.js)提个 PR。添加组件的脚本位于项目的 `scripts/add-component.js`。
> 
> macos可以替换名字，名字正确但是依然报错 <img alt="image" width="630" src="https://user-images.githubusercontent.com/43030980/177100901-5af06b82-080d-4f68-ad9b-6861b13902a3.png"> ![image](https://user-images.githubusercontent.com/43030980/177100937-fcbfca4f-e016-4395-a87b-dd5ec5688406.png)

请问解决了吗

**Comment by azhengyongqin** [comment]
# **KPI** 项目是真的辣鸡， 代码都跑不起来！

**windows**环境下把 `scripts/add-components.js`  中的代码替换成如下就可以替换模板了

```js

//old
const componentName = process.argv[2];
const templatePath = path.resolve(__dirname, "template");
const targetComponentPath = path.resolve(__dirname, `../components/${componentName}`);
const targetStoryPath = path.resolve(__dirname, `../stories`);

//new
const componentName = process.argv[2];
const templatePath = path.resolve(__dirname, "template").replace(/\\/g, "/");
const targetComponentPath = path.resolve(__dirname, `../components/${componentName}`).replace(/\\/g, "/");
const targetStoryPath = path.resolve(__dirname, `../stories`).replace(/\\/g, "/");

```

然而还是运行不起来，dev 运行还是报下面的错
![image](https://user-images.githubusercontent.com/18138282/213131606-ca30b4d4-690e-4710-8171-5cfc68ffc870.png)

**Comment by bqzhaoyan** [comment]
babel.config.js把这行注释一下













在 2023-01-18 17:18:22，"Rider" ***@***.***> 写道：

KPI 项目是真的辣鸡， 代码都跑不起来！

windows环境下把 scripts/add-components.js 中的代码替换成如下就可以替换模板了

//oldconstcomponentName=process.argv[2];consttemplatePath=path.resolve(__dirname,"template");consttargetComponentPath=path.resolve(__dirname,`../components/${componentName}`);consttargetStoryPath=path.resolve(__dirname,`../stories`);//newconstcomponentName=process.argv[2];consttemplatePath=path.resolve(__dirname,"template").replace(/\\/g,"/");consttargetComponentPath=path.resolve(__dirname,`../components/${componentName}`).replace(/\\/g,"/");consttargetStoryPath=path.resolve(__dirname,`../stories`).replace(/\\/g,"/");

然而还是运行不起来，dev 运行还是报下面的错
