### ISSUE TITLE
物料站点navbar自定义时会覆盖原先的登录操作，但是物料站点又需要一些登录信息，希望将登录封装成组件提供使用

### ISSUE THREAD

**Issue by ClayZth** [arco-design/arco-cli#46]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MisterLuffy** [comment]
通过 `window.arcoSiteGlobalComponents.UserLogin` 获取此组件，它可以接受[此物料](https://arco.bytedance.net/material/detail/?name=@arco-materials/navbar-user)的所有参数。
![image](https://user-images.githubusercontent.com/29861850/184110468-aed48df3-902f-4ca6-92aa-0b78d1b945f3.png)
