### ISSUE TITLE
工具库工程&文档能力支持

### ISSUE THREAD

**Issue by baby2011** [arco-design/arco-cli#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MisterLuffy** [comment]
可升级站点依赖 `arco-material-doc-site@1.14.1`，函数类型的物料文档将如下展示：
![image](https://user-images.githubusercontent.com/29861850/183868198-7bb760eb-768b-455b-bd8b-fbe07dcd4fbf.png)
