### ISSUE TITLE
总是会有这个异常出现，不知道怎么解决

### ISSUE THREAD

**Issue by ghost** [arco-design/arco-cli#51]
**Describe the bug**
Module parse failed unexpected token

**To Reproduce**
1. add component
2. yarn dev
3. Module parse failed unexpected token

**Expected behavior**
none

**Screenshots**
![origin_img_v2_b656b3a7-3fd4-4ad5-bc09-1a38a42b8c6g](https://user-images.githubusercontent.com/53162209/188904956-044ee021-50c4-4ab1-a96b-2df7240afb97.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - node version [e.g. v14.17.0]

**Additional context**
none

**Comment by MisterLuffy** [comment]
引入了什么其他的文件类型吗？拓展一下 Storybook 的 webpack 配置试试呢。
