### ISSUE TITLE
arco init 初始化有版本冲突

### ISSUE THREAD

**Issue by surrysom** [arco-design/arco-cli#55]
**Describe the bug**

**To Reproduce**
1. arco init azpro (arcodesign v1.27.3)
2. 请选择你希望使用的技术栈 Vue
3. 请选择所要创建项目的类型 Arco Pro 项目
4. 请选择 Arco Pro 模板 完整版（包含所有页面）
5. 项目依赖安失败，你可以稍后尝试手动安装项目依赖

Error: Command 「npm install」 executed failed:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: arco-design-pro-vue@1.0.0
npm ERR! Found: eslint@8.7.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb-base@14.2.1
npm ERR! node_modules/eslint-config-airbnb-base
npm ERR!   dev eslint-config-airbnb-base@"^14.2.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/wuhu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

 arco-init  项目初始化失败！
Error: spawnSync yarn ENOENT

**Desktop (please complete the following information):**
 - OS: [ MacOS 12.5]
 - node version [v16.18.0]

**Additional context**

**Comment by MisterLuffy** [comment]
可以尝试进到项目里边手动安装一下 NPM 依赖，如果仍然有问题可以去 [Arco Pro Vue 仓库](https://github.com/arco-design/arco-design-pro-vue) 提 Issue。

**Comment by bqzhaoyan** [comment]
> 可以尝试进到项目里边手动安装一下 NPM 依赖，如果仍然有问题可以去 [Arco Pro Vue 仓库](https://github.com/arco-design/arco-design-pro-vue) 提 Issue。

手动安装完报这个错
F:\vue3\lib-project>npm run dev
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> common-components@0.1.0 dev
> start-storybook -p 6006

info @storybook/vue3 v6.5.15
info
info => Loading presets
info => Loading custom babel config as JS
info Addon-docs: using MDX1
info => Using implicit CSS loaders
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/1 entries 0/0 dependencies 0/0 modules(node:14900) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Using prebuilt manager
99% done plugins webpack-hot-middlewarewebpack built preview ca4808d236a62eeb4d11 in 7914ms
ModuleNotFoundError: Module not found: Error: Can't resolve './stories' in 'F:\vue3\lib-project'
    at F:\vue3\lib-project\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\Compilation.js:2016:28
    at F:\vue3\lib-project\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\ContextModuleFactory.js:214:15
    at F:\vue3\lib-project\node_modules\neo-async\async.js:2830:7
    at F:\vue3\lib-project\node_modules\neo-async\async.js:6877:13
    at F:\vue3\lib-project\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\ContextModuleFactory.js:184:26
    at finishWithoutResolve (F:\vue3\lib-project\node_modules\@storybook\builder-webpack5\node_modules\enhanced-resolve\lib\Resolver.js:312:11)
    at F:\vue3\lib-project\node_modules\@storybook\builder-webpack5\node_modules\enhanced-resolve\lib\Resolver.js:386:15
    at F:\vue3\lib-project\node_modules\@storybook\builder-webpack5\node_modules\enhanced-resolve\lib\Resolver.js:435:5
    at eval (eval at create (F:\vue3\lib-project\node_modules\@storybook\builder-webpack5\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at F:\vue3\lib-project\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\cache\ResolverCachePlugin.js:257:15

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
