### ISSUE TITLE
windows 11 node 16.17.0 arco-cli init 报错，Error: spawn mkdir ENOENT

### ISSUE THREAD

**Issue by Oathkitchen** [arco-design/arco-cli#57]
**Describe the bug**
windows 11;
node 16.17.0;
arco-cli init 报错，Error: spawn mkdir ENOENT

**To Reproduce**
1. 在 windows terminal 中执行 `arco init test`

**Expected behavior**
成功拉去模板，并初始化项目

**Screenshots**
![image](https://user-images.githubusercontent.com/23115523/200764111-791c3380-6331-4ae7-b397-660bd418870c.png)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - node version [v16.17.0]

**Comment by MisterLuffy** [comment]
看起来到这一步项目已经初始化成功了，试一下可以运行吗？
