### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by sxt0215** [arco-design/arco-cli#58]
按照文档执行：

npm install --save-dev @arco-design/web-vue
npm i -g arco-cli

arco init hello

输出：

        ___                    ____            _
       /   |  ______________  / __ \___  _____(_)___ _____
      / /| | / ___/ ___/ __ \/ / / / _ \/ ___/ / __ `/ __ \
     / ___ |/ /  / /__/ /_/ / /_/ /  __(__  ) / /_/ / / / /
    /_/  |_/_/   \___/\____/_____/\___/____/_/\__, /_/ /_/
                                             /____/

                                                v1.27.3

(node:6969) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'question' of undefined
    at /usr/local/lib/node_modules/arco-cli/node_modules/arco-cli-dev-utils/lib/getAnswerFromUser.js:145:57
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/arco-cli/node_modules/arco-cli-dev-utils/lib/getAnswerFromUser.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6969) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6969) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MisterLuffy** [comment]
https://arco.design/material/api/cliConfig 这个接口可以访问到吗？
如果不能的话，可以尝试一下使用 `BASE_CONFIG=local arco init hello`
