### ISSUE TITLE
arco init [项目] 卡着不动

### ISSUE THREAD

**Issue by mmzzli** [arco-design/arco-cli#59]
**Describe the bug**
arco init [项目] 卡着不动

**To Reproduce**
1. npm install arco-cli -g
2. arco init hello-arco-pro
3. 
![image](https://user-images.githubusercontent.com/103935321/202990518-bf4b8363-346e-4c96-b4dc-d53f773ffd99.png)
4. 一直卡在这里不会动

**Screenshots**
![image](https://user-images.githubusercontent.com/103935321/202990518-bf4b8363-346e-4c96-b4dc-d53f773ffd99.png)
一直卡着
**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - node version [e.g. v18.12.0]

**Comment by Sunny-117** [comment]
我试一下没问题的，可能有点慢，停止重新试一下呢？
