### ISSUE TITLE
请提交你的 Git 修改后继续操作

### ISSUE THREAD

**Issue by Feng373712195** [arco-design/arco-cli#60]
**Describe the bug**
使用arco-cli初始化项目出现 _请提交你的 Git 修改后继续操作_ 提示，然后停止，不知道下一步如何操作。

**To Reproduce**
1. yarn global add arco-cli
2. 选择了公网版本
3. arco init 项目名称
4. 提示 请提交你的 Git 修改后继续操作

**Expected behavior**
成功初始化项目

**Screenshots**
<img width="942" alt="WeChatde746419b69ab690cb1d9c944a70dfb1" src="https://user-images.githubusercontent.com/21233482/203216034-a69f1af7-ffc8-45b7-9a9a-7c9d150f536f.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - node version [e.g. v14.19.1]
 - yarn version [e.g v1.22.10]

**Additional context**
初始化项目是在一个没有任何.git文件的文件夹下初始化的

**Comment by MisterLuffy** [comment]
`git status` 能执行吗？

**Comment by UsVfxArtia** [comment]
#65

**Comment by MisterLuffy** [comment]
`arco init` 时要求 Git 工作区是干净的，如果报上边的错请检查一下 `git status --short` 的执行结果。
