### ISSUE TITLE
arco-desigin-pro-vue项目的node_modules存在与之一样的文件内容

### ISSUE THREAD

**Issue by WestCraneLi** [arco-design/arco-cli#63]
**Describe the bug**
使用```arco init <programname>``` 创建arco-pro-vue项目，

**To Reproduce**
1. 创建：```arco init <programname>```
2. 报错：```commander erro: npm install```
3. 使用：```npm install --legacy-peer-deps```
4. 结果： ```node_modules```文件夹出现```arco-design-pro-vite```文件夹且根目录下的```package.json```有```dependencies:"arco-design-pro-vue": "^2.6.0"```

**Expected behavior**
创建完成的node_modules文件夹中不出现```arco-design-pro-vite```文件夹

**Desktop (please complete the following information):**
 - OS: Win10(Win32)
 - node version: v16.18.1
 - npm version:  v8.16.0

**Additional context**
* ```npm install``` 会报错：```ERESOLVE unable to resolve dependency tree;Could not resolve dependency:peer vite@"^4.0.0" from @vitejs/plugin-vue@4.0.0;node_modules/@vitejs/plugin-vue;dev @vitejs/plugin-vue@"^4.0.0" from the root project```

**Comment by MisterLuffy** [comment]
@sHow8e Please check this issue.
