### ISSUE TITLE
windows环境无法运行 exports is not defined

### ISSUE THREAD

**Issue by azhengyongqin** [arco-design/arco-cli#64]
@MisterLuffy  https://github.com/arco-design/arco-cli/issues/38#issuecomment-1170710705

Windows环境下依然报错，麻烦解决windows下的环境
![image](https://user-images.githubusercontent.com/18138282/213135125-8a4205b1-2ca8-4f4d-817b-1833f343e079.png)

_Originally posted by @azhengyongqin in https://github.com/arco-design/arco-cli/issues/38#issuecomment-1386749538_

**Comment by MisterLuffy** [comment]
这看起来是一个 Storybook 的配置问题，可以搜索一下 Storybook 的 Issue。刚才简单尝试了一下没有解决，如果解决了请在下边评论，我会去更新项目的默认配置。
