### ISSUE TITLE
Cannot create project - Please commit your Git modification first

### ISSUE THREAD

**Issue by UsVfxArtia** [arco-design/arco-cli#65]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-cli/issues)

## Basic Info 
- **Package Name And Version:** arco-cli@1.27.4
- **Framework version:** Cant even use
- **Browser:** chrome106.0.0.0

## Extra info
No errors, it just says - Please commit your Git modification first

## What is expected?
Generated Project

## Steps to reproduce
1) npm i arco-cli@latest
2) arco init arco-hello-world

**Comment by MisterLuffy** [comment]
Same with #60
